config/routes.rb
RoutesApp::Application.routes.draw do  
  resources :products do
    resource :duplicate, :controller => 'duplicates', :only => [:new, :create]
  end
  
  # get 'products/duplicate/:id' => 'products#new_duplicate', :as => 'new_duplicate'
  # post 'products/duplicate/:id' => 'products#create_duplicate'
  
  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/duplicates_controller.rb
class DuplicatesController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @all_products = Product.where(['id <> ?', params[:product_id]])
  end
  
  def create
    @product = Product.find(params[:product_id])
    @duplicate_of = Product.find(params[:duplicate_of_id])
    @product.duplicate = true
    @product.duplicate_of = @duplicate_of.id
    if @product.save
      redirect_to products_path
    else
      render 'new_duplicate'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(:duplicate => false)
  end

  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    @product.category = "New"
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/duplicates_helper.rb
module DuplicatesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/duplicates/new.html.erb
<h1>Mark <%= @product.name %> as Duplicate</h1>
<h4>Listed in <%= @product.category %></h4>
<p><%= @product.description %></p>

<%= form_tag(:action => "create") do %>
  <h2>This is a duplicate of:</h2>
  
  <%= select_tag(:duplicate_of_id, options_from_collection_for_select(@all_products, :id, :name)) %>
  
  <%= submit_tag('Mark as Duplicate') %>
<% end %>

<%= link_to 'Back to All products', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoutesApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>
<%= form_for(@product) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>
<h4><%= link_to 'New Product', new_product_path %></h4>
<ul>
  <% @products.each { |p| %>
    <li>
      <h3><%= p.name %></h3>
      <h4>Listed in <%= p.category %></h4>
      <p><%= p.description %></p>
      <%= link_to 'View', product_path(p) %>
      <%= link_to 'Edit', edit_product_path(p) %>
      <%= link_to 'Duplicate', new_product_duplicate_path(p) %>
    </li>
  <% } %>
</ul>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for(@product) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h4>Listed in <%= @product.category %></h4>
<p><%= @product.description %></p>
<%= link_to 'All products', products_path %>